### ISSUE TITLE
Add N8 workshops to workshop history of carpentries GPU lesson

### ISSUE THREAD

**Issue by svenvanderburg** [ARCLeeds/lesson-gpu-programming#4]
Could you add the editions of this workshops to https://github.com/carpentries-incubator/lesson-gpu-programming/blob/4e81238b5c2c140106ee753a07b1a77d32269cc1/workshops.md ? It helps us show the impact of open-source lesson development to our funders :)

**Comment by svenvanderburg** [comment]
Or if you can give me the date, host organisation, location I can add it :)

**Comment by svenvanderburg** [comment]
@Sparrow0hawk

**Comment by Sparrow0hawk** [comment]
Hi,

This workshop was ran in two halves on 9th March 2023 (in person in Newcastle) and 18th April 2023 (virtual).

It was organised for UK academic researchers at the N8 consortium of universities by the N8 computational intensive research (CIR) centre of excellence.

https://n8cir.org.uk/events/python-gpu-programming-workshop/

Hope that helps,

Alex

**Comment by svenvanderburg** [comment]
Thank you @Sparrow0hawk :pray: 

Added it to the file with https://github.com/carpentries-incubator/lesson-gpu-programming/pull/114/commits/c32c9236dbf367f48ada736e9f888614912f9ac4
